#!/bin/sh /etc/rc.common

NAME='srun_login'
START=99
USE_PROCD=1
PROG=/usr/bin/node
SCRIPT=/usr/local/srun_login/login.js

start_service() {
    procd_open_instance
    procd_set_param command $PROG $SCRIPT
    procd_set_param pidfile /var/run/srun_login.pid
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
    procd_close_instance
}